; Configuration additionnelle pour OTA-1.1.
; Utiliser avec : pio run -c platformio_ota.ini -e ProgrammeArrosage_ota_tls_probe

[platformio]
extra_configs = platformio.ini

[env:ProgrammeArrosage_ota_tls_probe]
extends = env:ProgrammeArrosage
upload_port = COM3
monitor_port = COM3
build_flags =
    ${env:ProgrammeArrosage.build_flags}
    -DAQUALOOK_OTA_TLS_PROBE=1
